[build]
builder = "nixpacks"
nixpacksPlan = "npm install && npm run build"
nixpacksVersion = "latest"

[deploy]
startCommand = "npm start"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10